development: &default
  adapter: postgresql
  database: litmus_status_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: litmus_status_test

production: &deploy
  database: litmus_status_production
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
